added DEHYDRATED param to define the dehydrated binary

diff --git a/dehydrated-renew b/dehydrated-renew
--- a/dehydrated-renew
+++ b/dehydrated-renew
@@ -29,7 +29,11 @@ fi
 
 rm -f $CERT_CHANGED_FLAG
 
-/usr/bin/dehydrated -c -g
+if [ -z "$DEHYDRATED" ]; then
+  echo "dehydrated not found" >&2
+  exit 1
+fi
+$DEHYDRATED -c -g
 
 if [ -f $CERT_CHANGED_FLAG ]; then
   cert_sync
